name: accurative
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.3.3

  #* State management
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5

  #* UI
  google_fonts: 6.1.0
  shimmer: ^3.0.0

  #* Dependency Injection
  get_it: ^7.6.4

  #* Routing
  get: ^4.6.6

  #* Utils
  dartz: ^0.10.1
  flutter_keyboard_visibility: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
