name: alarm
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* Network
  dio: ^5.4.1

  #* State management
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5

  #* UI
  fluttertoast: ^8.1.0
  shimmer: ^3.0.0

  #* Dependency Injection
  get_it: ^7.6.4

  #* Routing
  get: ^4.6.6

  #* Storage
  flutter_secure_storage: ^9.2.2

  #* Notification
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  timezone: ^0.9.3

  #* Utils
  fpdart: ^1.1.0
  flutter_keyboard_visibility: ^6.0.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  uuid: ^4.2.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
